name: Publish to NPM

on:
  release:
    types: [created]

defaults: 
  run:
    working-directory: ./package/package

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
        - run: npm ci
        - run: npm run build
        - name: Publish on NPM
          run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}